# Generated by Django 3.1.6 on 2021-06-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=10, verbose_name='ツールのアカウント名')),
                ('item_name', models.CharField(max_length=10, verbose_name='商品名')),
                ('price', models.CharField(max_length=10, verbose_name='価格')),
                ('item_id', models.CharField(max_length=10, verbose_name='商品の個別ID')),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('image3', models.ImageField(upload_to='')),
                ('image4', models.ImageField(upload_to='')),
                ('auction', models.CharField(choices=[('メルカリ', 'メルカリ'), ('ラクマ', 'ラクマ')], default='メルカリ', max_length=10, verbose_name='メルカリ/ラクマ選択')),
            ],
        ),
    ]
