# Generated by Django 3.1.6 on 2021-06-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_itemdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_list', models.CharField(max_length=100)),
            ],
        ),
    ]
