# Generated by Django 3.1.6 on 2021-07-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_urllist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyuppinItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=10, verbose_name='商品名')),
                ('price', models.CharField(max_length=10, verbose_name='価格')),
                ('seller_name', models.CharField(max_length=50, verbose_name='販売者名')),
                ('image_url1', models.CharField(max_length=50, verbose_name='画像URL')),
                ('url', models.CharField(max_length=50, verbose_name='URL')),
                ('site', models.CharField(max_length=10, verbose_name='サイト')),
            ],
        ),
    ]
