# Generated by Django 3.1.6 on 2021-07-01 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0004_syuppinitem'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='syuppinitem',
            table='aaaaaaa',
        ),
    ]
