# Generated by Django 3.1.6 on 2021-07-01 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0005_auto_20210701_1001'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='syuppinitem',
            table='a_syuppin_item',
        ),
    ]
